version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kyoso-dev-postgres
    environment:
      POSTGRES_USER: kyoso
      POSTGRES_PASSWORD: kyoso
      POSTGRES_DB: kyoso
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '3010:5432'

  minio:
    image: minio/minio
    container_name: kyoso-dev-minio
    environment:
      MINIO_ROOT_USER: kyoso
      MINIO_ROOT_PASSWORD: kyoso123
    command: server /data --address :9000 --console-address :9001
    volumes:
      - minio_data:/data
    ports:
      - '3011:9000'
      - '3012:9001'

  redis:
    image: redis:7
    container_name: kyoso-dev-redis
    command: ['redis-server', '--requirepass', 'kyoso']
    ports:
      - '3013:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  minio_data:
  redis_data:
