version: '3.8'

volumes:
  pgdata:

services:
  kyoso-db:
    container_name: kyoso-db
    image: postgres:15.2-alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kyoso
      POSTGRES_PORT: 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
