name: Code Review
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'development'
      ENV: 'development'
      DATABASE_URL: 'postgresql://example:example@localhost:5432/example'
      JWT_SECRET: 'secret'
      CRON_SECRET: 'secret'
      OWNER: '1'
      TESTERS: '[1]'
      PUBLIC_CONTACT_EMAIL: 'example@example.com'
      PUBLIC_OSU_CLIENT_ID: '1'
      OSU_CLIENT_SECRET: 'secret'
      PUBLIC_OSU_REDIRECT_URI: 'http://localhost:5173/api/auth/callback/osu'
      PUBLIC_DISCORD_CLIENT_ID: '1'
      DISCORD_CLIENT_SECRET: 'secret'
      PUBLIC_DISCORD_MAIN_REDIRECT_URI: 'http://localhost:5173/api/auth/callback/discord'
      PUBLIC_DISCORD_CHANGE_ACCOUNT_REDIRECT_URI: 'http://localhost:5173/api/auth/callback/discord/change'
      DISCORD_BOT_TOKEN: 'token'
      BUNNY_HOSTNAME: 'example.bunnycdn.com'
      BUNNY_USERNAME: 'username'
      BUNNY_PASSWORD: 'password'
      IPINFO_ACCESS_TOKEN: 'token'
      UPSTASH_REDIS_REST_URL: 'example.upstash.io'
      UPSTASH_REDIS_REST_TOKEN: 'token'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Svelte Check
        run: pnpm check
